const ENTITY_CAP = 8192;
function mix32(v: number) { v = Math.imul(v ^ (v >>> 16), 0x7feb352d); v = Math.imul(v ^ (v >>> 15), 0x846ca68b); return (v ^ (v >>> 16)) >>> 0; }
export class FightChantVoice {
  private readonly lastByActor = new Float64Array(ENTITY_CAP); private voices: SpeechSynthesisVoice[] = []; private pending = 0; private attached = false;
  constructor() { if (typeof window === "undefined" || !("speechSynthesis" in window)) return; this.refreshVoices(); window.speechSynthesis.addEventListener("voiceschanged", this.refreshVoices); this.attached = true; }
  speak(actorId: number, mag: number) { if (typeof window === "undefined" || !("speechSynthesis" in window) || typeof SpeechSynthesisUtterance === "undefined") return; const now = typeof performance !== "undefined" ? performance.now() * 0.001 : 0; if (actorId >= 0 && actorId < ENTITY_CAP) { if (now - this.lastByActor[actorId]! < 0.55) return; this.lastByActor[actorId] = now; } if (this.pending >= 2) return; if (!this.voices.length) this.refreshVoices(); const h = mix32((actorId + 1) * 0x9e3779b1); const u = new SpeechSynthesisUtterance("FIGHT!"); if (this.voices.length) u.voice = this.voices[h % this.voices.length]!; u.rate = 1.16 + ((h >>> 8) & 255) / 255 * 0.34; u.pitch = 0.78 + ((h >>> 16) & 255) / 255 * 0.5; u.volume = Math.max(0.35, Math.min(1, 0.42 + mag * 0.45)); this.pending++; const done = () => { this.pending = Math.max(0, this.pending - 1); }; u.onend = done; u.onerror = done; window.speechSynthesis.speak(u); }
  dispose() { if (typeof window !== "undefined" && this.attached && "speechSynthesis" in window) window.speechSynthesis.removeEventListener("voiceschanged", this.refreshVoices); this.attached = false; this.pending = 0; }
  private refreshVoices = () => { if (typeof window === "undefined" || !("speechSynthesis" in window)) return; const all = window.speechSynthesis.getVoices(); const english = all.filter((v) => /^en(?:-|_)/i.test(v.lang)); this.voices = english.length ? english : all.slice(); };
}
